Name:Ankit Gaidhar

Practical_5_2

Roll_no:D2_28

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('insurance.csv')

In [ ]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df['sex']=df['sex'].replace('female',0)
df['sex']=df['sex'].replace('male',1)

In [ ]:
df.head()

age  sex     bmi  children smoker     region      charges
0   19    0  27.900         0    yes  southwest  16884.92400
1   18    1  33.770         1     no  southeast   1725.55230
2   28    1  33.000         3     no  southeast   4449.46200
3   33    1  22.705         0     no  northwest  21984.47061
4   32    1  28.880         0     no  northwest   3866.85520

In [ ]:
df['smoker']=df['smoker'].replace('yes',1)
df['smoker']=df['smoker'].replace('no',0)

In [ ]:
df.head()

age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [ ]:
# Get unique entries in the 'Category' column
unique_entries = df['region'].unique()
unique_entries

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
df.region=df.region.map({'northeast':1,'northwest':2,'southeast':3,'southwest':4})
df.region

0       4
1       3
2       3
3       2
4       2
       ..
1333    2
1334    1
1335    3
1336    4
1337    2
Name: region, Length: 1338, dtype: int64

In [ ]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       4  16884.92400
1      18    1  33.770         1       0       3   1725.55230
2      28    1  33.000         3       0       3   4449.46200
3      33    1  22.705         0       0       2  21984.47061
4      32    1  28.880         0       0       2   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       2  10600.54830
1334   18    0  31.920         0       0       1   2205.98080
1335   18    0  36.850         0       0       3   1629.83350
1336   21    0  25.800         0       0       4   2007.94500
1337   61    0  29.070         0       1       2  29141.36030

[1338 rows x 7 columns]

In [ ]:

from sklearn.model_selection import train_test_split


In [ ]:
X =df.drop(['charges'],axis='columns')  # Your feature data
Y =df.drop(['age','sex','bmi','children','smoker','region'],axis='columns')# Your target variable

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


In [ ]:
X_train.shape

(1070, 6)

In [ ]:
X_test.shape

(268, 6)

In [ ]:
from sklearn.linear_model import LinearRegression
reg= LinearRegression()
reg.fit(X_train,Y_train)

LinearRegression()

In [ ]:
y_test_predict= reg.predict(X_test)
y_test_predict

array([[ 8924.40724442],
       [ 7116.29501758],
       [36909.01352144],
       [ 9507.87469118],
       [27013.3500079 ],
       [10790.77956153],
       [  226.29844571],
       [16942.71599941],
       [ 1056.63079407],
       [11267.91997309],
       [28048.59793155],
       [ 9424.36324087],
       [ 5326.32232088],
       [38460.06017922],
       [40303.40597026],
       [37147.01010262],
       [15287.91876684],
       [35965.05485917],
       [ 9179.1753067 ],
       [31510.8319849 ],
       [ 3797.79068365],
       [10070.82803304],
       [ 2312.57551348],
       [ 7074.41348194],
       [11352.37224357],
       [12907.77079523],
       [14448.84678727],
       [ 6205.65997921],
       [ 9917.00839638],
       [ 2239.50032819],
       [ 9060.55469043],
       [13120.56214535],
       [ 4617.70702822],
       [ 3467.91218926],
       [ 4402.74821855],
       [12967.91608907],
       [ 1927.44498944],
       [ 8757.9180081 ],
       [33324.35180597],
       [32638.47697026],


In [ ]:
X_test.shape

(268, 6)

In [ ]:
Y_test.shape

(268, 1)

In [ ]:
c=reg.intercept_
c

array([-11675.32230125])

In [ ]:
m = reg.coef_
m

array([[ 2.57056264e+02, -1.87914567e+01,  3.35781491e+02,
         4.25091456e+02,  2.36478181e+04, -2.71284266e+02]])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(Y_test,y_test_predict )

0.7833463107364539